// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjC820vlhFfKAEF4gXPdvWqWnmQm_pz3Q',
    appId: '1:92724783724:web:5e8e2d0eea54dcf7398649',
    messagingSenderId: '92724783724',
    projectId: 'stkodds',
    authDomain: 'stkodds.firebaseapp.com',
    storageBucket: 'stkodds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm8FwU-NYCvNaLyk-jKdqjnhsVnjSZIXI',
    appId: '1:92724783724:android:061ca970ff554574398649',
    messagingSenderId: '92724783724',
    projectId: 'stkodds',
    storageBucket: 'stkodds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpOM_fmAOk_h4bWl1I5X4hF99MpccUl2Q',
    appId: '1:92724783724:ios:420bc7e331f12bfa398649',
    messagingSenderId: '92724783724',
    projectId: 'stkodds',
    storageBucket: 'stkodds.firebasestorage.app',
    iosBundleId: 'com.stkodds.stkodds',
  );
}
